### ISSUE TITLE
Recuperare accettazione e consegna messaggio

### ISSUE THREAD

**Issue by kiks73** [lucasaba/php-pec#3]
Mi chiedevo se c'è una best practice per poter effettuare il match tra la mail inviata e le accettazioni e consegne che trovo leggendo la mail. 
Io pensavo di utilizzare l'oggetto della mail ricercando la substring "ACCETTAZIONE:" e "CONSEGNA:" seguito dall'oggetto della mail originariamente inviata.
E' possibile filtrare i messaggi senza doverli prima scaricare tutti e poi ciclarli da client?

**Comment by lucasaba** [comment]
La versione breve della risposta è si, devi filtrare sull'oggetto.

Versione lunga: il problema è che l'RFC della PEC è strutturata in modo un po particolare... Ci sono una serie di richieste allo IANA (https://tools.ietf.org/html/rfc6109#section-8.1) per standardizzare le intestazione del messaggio ma, devo essere sincero, non mi fido a seguire quella strada perché, ad ora, la PEC è solo una cosa italiana.
Da qui https://tools.ietf.org/html/rfc6109#section-3.2 sembra che l'unico modo sicuro di riconoscere un tipo di ricevuta sia facendo parsing del testo contenuto nel titolo o nel corpo della mail principale (la busta della pec).

Personalmente, per leggere i messaggi PEC in ingresso uso:
```php
foreach ($server->recuperaPecInIngresso('SUBJECT "POSTA CERTIFICATA: " UNSEEN') as $messaggio) {
```

Per quel che riguarda le ricevute, il discorso è più lungo. O recuperi tutti i messaggi e procedi a filtrarli a mano. Oppure devi fare una chiamata per filtrare i messaggi a seconda del tipo di ricevuta (accettazione, non-accettazione, presa-in-carico, avvenuta-consegna, posta-certificata, errore-consegna, preavviso-errore-consegna, rilevazione-virus). A dire il vero....sono entrambi tediosi.... Per semplificare il flusso, una volta trattata la ricevuta, la sposto in una cartella a parte (via imap) per evitare di rileggere ogni volta tuuuuuutti i messaggi.

Il tipo ricevuta viene restituito dall'oggetto PECMessage (che estende l'oggetto [Message](https://github.com/tedious/Fetch/blob/master/src/Fetch/Message.php) ).

**Comment by cartenca** [comment]
E' possibile usare una funzione per spostare un' email PEC in una sottocartella?
Grazie
Carlo

**Comment by lucasaba** [comment]
No. Per fare lo spostamento dovrai usare le funzioni IMAP.
In un mio progetto uso i metodi che puoi vedere qui: https://gist.github.com/lucasaba/e2289aa8b423f2adf448562557ff5709

Considera che Mailbox è un oggetto che contiene le informazioni per il login alla mail-box della pec (host, porta, nome utente e password).
