### ISSUE TITLE
creazione EML

### ISSUE THREAD

**Issue by giovannib** [lucasaba/php-pec#5]
Ciao Luca.
Grazie per quello cha hai implementato.
Ho un problema relativamente alla creazione degli EML con e senza attachments.

$server = new PecServer("imaps.pec.aruba.it", 993);
$server->setAuthentication($pec_sistema, $password_pec_sistema);
$server->setParam('DISABLE_AUTHENTICATOR', 'PLAIN');
$messages = $server->recuperaPecInIngresso();
foreach ($messages as $message) {
[...]
leggo corretamente oggetto, testo, date....
Quando vado a salvare l'EML con tutti i dati nelle relative variabili, in questo modo:

file_put_contents($fileName, $message->getRawHeaders() . "\n" . $message->getMessageBody());

e lo apro con Outlook, questo lo interpreta come "testo normale" e quindi vedo ogni informazione della pec "appiccicati" al testo. Es:

![immagine](https://user-images.githubusercontent.com/5058043/100084467-171af680-2e4b-11eb-8a06-d0438ebccfcb.png)

Ho provato inoltre a sostituire  "\n" con  "\r\n", oppure a togliere entrambi ma senza successo. 

Aggiungo che ho necessità di copiare ogni elemento (comprese ricevute) e l'oggetto di ogni pec è "CONSEGNA:" (che ho correttamente filtrato).

Hai qualche suggerimento da fornirmi?
Grazie

**Comment by lucasaba** [comment]
Ciao @giovannib , grazie a te per usarlo e scusami se ancora non è per niente completo ;(

Comunque, ad una prima veloce occhiata, potrebbe essere che ti serve una riga vuota tra header e body. Quindi, dovresti sostituire l "\n" con "\r\n\r\n".

~~Secondariamente, forse c'è un metodo più semplice per avere il dato grezzo. Lo trovi nel metodo [getRawBody](https://github.com/lucasaba/php-pec/blob/master/src/PhpPec/PecMessage.php#L288) di PECMessage. Dovrebbe restituire il dato grezzo fresco fresco da imap.~~

**Comment by giovannib** [comment]
Fantastico!! Ho appena provato a utilizzare il getRawBody (che non avevo visto). Funziona alla grande!
Grazie del supporto!
Buon lavoro

**Comment by lucasaba** [comment]
:rofl: Pensa che l'avevo cancellato perché mi era parso che lo usassi già!

È stato un piacere :+1:
